/*****************************************************************************
* Model: aquarium.qm
* File:  ./aquarium.h
*
* This file has been generated automatically by QP Modeler (QM).
* DO NOT EDIT THIS FILE MANUALLY.
*
* Please visit www.state-machine.com/qm for more information.
*****************************************************************************/
#ifndef aquarium_h
#define aquarium_h

enum AquariumSignals {
    PAUSE_SIG = Q_USER_SIG,/* published by BSP to pause the application */
    RESUME_SIG,
    MAX_PUB_SIG,          /* the last published signal */
    MAX_SIG               /* the last signal */
};


#endif //aquarium_h
