# Invoke with this make command:
TARGET := loop
LIBSRC :=
APP_CFLAGS := -I../timespec -I../rtdb
APP_LDFLAGS := -L../timespec -ltimespec -L../rtdb -lrtdb -pthread -lrt
include ../base.mk ##################################
