/*****************************************************************************
* Model: dpp.qm
* File:  ./table.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${.::table.c} ............................................................*/
#include "qpc.h"
#include "dpp.h"
#include "bsp.h"
#include "msg.h"

//Q_DEFINE_THIS_FILE

/* Active object class -----------------------------------------------------*/
/*${AOs::Table} ............................................................*/
typedef struct {
/* protected: */
    QActive super;

/* private: */
} Table;

/* Local objects -----------------------------------------------------------*/
static Table l_table; /* the single instance of the Table active object */

/* Global-scope objects ----------------------------------------------------*/
QActive * const AO_Table = &l_table.super; /* "opaque" AO pointer */

static QState Table_active(Table* const me, QEvt const* const e) {
	switch(e->sig) {
	case NUS_SIG: {
		const NUSEvt* pe = (const NUSEvt*)e;
		switch(pe->type) {
		case MSG_STATE: // state query
			MSG_BEGIN(MSG_STATE);
			MSG_I16(TABLE_STATE_ACTIVE | AO_TABLE);
			MSG_END();
			break;
		default: break;
		}
	} return Q_HANDLED();
	default:
		return Q_SUPER(&QHsm_top);
	}
}

static QState Table_initial(Table* const me, QEvt const* const e) {
    /* ${AOs::Table::SM::initial} */
    uint8_t n;
    (void)e; /* suppress the compiler warning about unused parameter */

    QS_OBJ_DICTIONARY(&l_table);
    QS_FUN_DICTIONARY(&QHsm_top);
    QS_FUN_DICTIONARY(&Table_initial);
    QS_FUN_DICTIONARY(&Table_active);

    QS_SIG_DICTIONARY(NUS_SIG, (void *)0);

    QActive_subscribe(&me->super, NUS_SIG);

    return Q_TRAN(&Table_active);
}

void Table_ctor(void) {
    uint8_t n;
    Table *me = &l_table;

    QActive_ctor(&me->super, Q_STATE_CAST(&Table_initial));
}
